// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace shopsyApi.Models;

public partial class AppliedCoupon
{
    public int AppliedCouponId { get; set; }

    public int OrderId { get; set; }

    public int CouponId { get; set; }

    public decimal DiscountApplied { get; set; }
}