// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace shopsyApi.Models;

public partial class Coupon
{
    public int CouponId { get; set; }

    public string Code { get; set; }

    public decimal Discount { get; set; }

    public DateOnly ExpiryDate { get; set; }

    public decimal? MinOrderAmount { get; set; }

    public decimal? MaxDiscountAmount { get; set; }

    public bool? IsActive { get; set; }
}