// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace shopsyApi.Models;

public partial class Shipping
{
    public int ShippingId { get; set; }

    public int OrderId { get; set; }

    public int AddressId { get; set; }

    public string ShippingMethod { get; set; }

    public string ShippingStatus { get; set; }

    public string TrackingNumber { get; set; }

    public DateOnly? EstimatedDelivery { get; set; }
}